### PR TITLE
Player handling

### PR DESCRIPTION
**Pull request by aenachescu**
I created the functions for adding and removing of a player in/from a team.

### CODE REVIEW

**Comment by flavius** [comment]
@EnachescuAlin You should synchronize the two branches before sending a pull request, so that in the pull request appear only the commits which are actually relevant to... the pull request

@Paul92 you should make sure that the above is respected. It's common sense.

**Comment by Paul92** [comment]
@flavius What do you mean by "synchronize the two branches"? 
@EnachescuAlin should have merged his branch into his develop and then make the pull request?

**Comment by flavius** [comment]
I haven't read all those commits, but are they all relevant to one single issue?

Or are they fixing problems which don't have opened issues? (which wouldn't be a problem).

I've just skimmed throgh this PR and the number of commits looks suspiciously high.

**Comment by Paul92** [comment]
Yes, they are related to this issue. The number of commits is so large because the function has been reviewed and refactored all over again.

**Pull request merged**
