### PR TITLE
Hacking

### PR DESCRIPTION
**Pull request by Paul92**

### CODE REVIEW

**Comment by flavius** [comment]
@Paul92 Tough question. semver looks more like a specification which can be referenced, the branching model looks more like a drawing. You decide.

The problem is that web sites can go down and never come back up online again.

**Comment by Paul92** [comment]
Then, the link with semversion can't go down too? :). 
Anyway, I tried to make a short resumee on what is on those sites (that is to be used in our project), with small modifications. Wouldn't it be better if I leave that as it is and add the link as a reference for more details?

**Comment by flavius** [comment]
semver can go down too, but it is an effort of a group, not a blog article of an individual, and it's referenced by a bunch of important and big projects.

You decide how to do it, I was just raising a question.

**Comment by Paul92** [comment]
I added the link as a reference. I leaved the additions and the parts of that reference that I think are the most relevant to our project.

**Pull request merged**
