### PR TITLE
269

### PR DESCRIPTION
**Pull request by JustBeYou**

### CODE REVIEW

**Comment by JustBeYou** [comment]
I corrected the commits, this can be merged, I think.

**Comment by JustBeYou** [comment]
Lib CLI created. Bugs fixed. Task done.

**Comment by Paul92** [comment]
Use yellow to highlight the current selection, since this is the standard throughout the application. Also, for some reason, if I select the third option (help), the application crashes with a seg fault. Also, do not open other pull requests. Just do your thing on this branch.

**Comment by JustBeYou** [comment]
It is strange that help option crash. On my machine it doesn't. I think it is undefined behavior, I'll fix it.

**Comment by JustBeYou** [comment]
I changed the color to yellow, by the way it looks very strange on my computer, much like orange, not yellow, maybe my terminal settings affect this.

**Pull request merged**
